<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PhysioReflexExamination extends Model
{
    use HasFactory;

    protected $table = 'physio_reflex_examinations';

    public $timestamps = false;
    protected $fillable = [
        'moro_result',
        'moro_primitive',
        'moro_functional',
        'moro_pathological',
        'moro_integration',
        'moro_not_synchronous',
        'blinking_result',
        'blinking_primitive',
        'blinking_functional',
        'blinking_pathological',
        'blinking_integration',
        'blinking_not_synchronous',
        'galant_result',
        'galant_primitive',
        'galant_functional',
        'galant_pathological',
        'galant_integration',
        'galant_not_synchronous',
        'atnr_result',
        'atnr_primitive',
        'atnr_functional',
        'atnr_pathological',
        'atnr_integration',
        'atnr_not_synchronous',
        'stnr_result',
        'stnr_primitive',
        'stnr_functional',
        'stnr_pathological',
        'stnr_integration',
        'stnr_not_synchronous',
        'sucking_result',
        'sucking_primitive',
        'sucking_functional',
        'sucking_pathological',
        'sucking_integration',
        'sucking_not_synchronous',
        'rooting_result',
        'rooting_primitive',
        'rooting_functional',
        'rooting_pathological',
        'rooting_integration',
        'rooting_not_synchronous',
        'palmar_grasps_result',
        'palmar_grasps_primitive',
        'palmar_grasps_functional',
        'palmar_grasps_pathological',
        'palmar_grasps_integration',
        'palmar_grasps_not_synchronous',
        'plantar_grasps_result',
        'plantar_grasps_primitive',
        'plantar_grasps_functional',
        'plantar_grasps_pathological',
        'plantar_grasps_integration',
        'plantar_grasps_not_synchronous',
        'flexor_withdrawal_result',
        'flexor_withdrawal_primitive',
        'flexor_withdrawal_functional',
        'flexor_withdrawal_pathological',
        'flexor_withdrawal_integration',
        'flexor_withdrawal_not_synchronous',
        'babinsky_result',
        'babinsky_primitive',
        'babinsky_functional',
        'babinsky_pathological',
        'babinsky_integration',
        'babinsky_not_synchronous',
        'righting_result',
        'righting_primitive',
        'righting_functional',
        'righting_pathological',
        'righting_integration',
        'righting_not_synchronous',
        'automatic_gait_reflex_result',
        'automatic_gait_reflex_primitive',
        'automatic_gait_reflex_functional',
        'automatic_gait_reflex_pathological',
        'automatic_gait_reflex_integration',
        'automatic_gait_reflex_not_synchronous',
        'parachute_result',
        'parachute_primitive',
        'parachute_functional',
        'parachute_pathological',
        'parachute_integration',
        'parachute_not_synchronous',
        'landau_result',
        'landau_primitive',
        'landau_functional',
        'landau_pathological',
        'landau_integration',
        'landau_not_synchronous',
        'protective_reflex_result',
        'protective_reflex_primitive',
        'protective_reflex_functional',
        'protective_reflex_pathological',
        'protective_reflex_integration',
        'protective_reflex_not_synchronous',
    ];

    protected $casts = [
        'moro_primitive' => 'boolean',
        'moro_functional' => 'boolean',
        'moro_pathological' => 'boolean',
        'moro_integration' => 'boolean',
        'moro_not_synchronous' => 'boolean',
        'blinking_primitive' => 'boolean',
        'blinking_functional' => 'boolean',
        'blinking_pathological' => 'boolean',
        'blinking_integration' => 'boolean',
        'blinking_not_synchronous' => 'boolean',
        'galant_primitive' => 'boolean',
        'galant_functional' => 'boolean',
        'galant_pathological' => 'boolean',
        'galant_integration' => 'boolean',
        'galant_not_synchronous' => 'boolean',
        'atnr_primitive' => 'boolean',
        'atnr_functional' => 'boolean',
        'atnr_pathological' => 'boolean',
        'atnr_integration' => 'boolean',
        'atnr_not_synchronous' => 'boolean',
        'stnr_primitive' => 'boolean',
        'stnr_functional' => 'boolean',
        'stnr_pathological' => 'boolean',
        'stnr_integration' => 'boolean',
        'stnr_not_synchronous' => 'boolean',
        'sucking_primitive' => 'boolean',
        'sucking_functional' => 'boolean',
        'sucking_pathological' => 'boolean',
        'sucking_integration' => 'boolean',
        'sucking_not_synchronous' => 'boolean',
        'rooting_primitive' => 'boolean',
        'rooting_functional' => 'boolean',
        'rooting_pathological' => 'boolean',
        'rooting_integration' => 'boolean',
        'rooting_not_synchronous' => 'boolean',
        'palmar_grasps_primitive' => 'boolean',
        'palmar_grasps_functional' => 'boolean',
        'palmar_grasps_pathological' => 'boolean',
        'palmar_grasps_integration' => 'boolean',
        'palmar_grasps_not_synchronous' => 'boolean',
        'plantar_grasps_primitive' => 'boolean',
        'plantar_grasps_functional' => 'boolean',
        'plantar_grasps_pathological' => 'boolean',
        'plantar_grasps_integration' => 'boolean',
        'plantar_grasps_not_synchronous' => 'boolean',
        'flexor_withdrawal_primitive' => 'boolean',
        'flexor_withdrawal_functional' => 'boolean',
        'flexor_withdrawal_pathological' => 'boolean',
        'flexor_withdrawal_integration' => 'boolean',
        'flexor_withdrawal_not_synchronous' => 'boolean',
        'babinsky_primitive' => 'boolean',
        'babinsky_functional' => 'boolean',
        'babinsky_pathological' => 'boolean',
        'babinsky_integration' => 'boolean',
        'babinsky_not_synchronous' => 'boolean',
        'righting_primitive' => 'boolean',
        'righting_functional' => 'boolean',
        'righting_pathological' => 'boolean',
        'righting_integration' => 'boolean',
        'righting_not_synchronous' => 'boolean',
        'automatic_gait_reflex_primitive' => 'boolean',
        'automatic_gait_reflex_functional' => 'boolean',
        'automatic_gait_reflex_pathological' => 'boolean',
        'automatic_gait_reflex_integration' => 'boolean',
        'automatic_gait_reflex_not_synchronous' => 'boolean',
        'parachute_primitive' => 'boolean',
        'parachute_functional' => 'boolean',
        'parachute_pathological' => 'boolean',
        'parachute_integration' => 'boolean',
        'parachute_not_synchronous' => 'boolean',
        'landau_primitive' => 'boolean',
        'landau_functional' => 'boolean',
        'landau_pathological' => 'boolean',
        'landau_integration' => 'boolean',
        'landau_not_synchronous' => 'boolean',
        'protective_reflex_primitive' => 'boolean',
        'protective_reflex_functional' => 'boolean',
        'protective_reflex_pathological' => 'boolean',
        'protective_reflex_integration' => 'boolean',
        'protective_reflex_not_synchronous' => 'boolean',
    ];
}
